# Site settings
title: Confessions of a developer mind
description: > # this means to ignore newlines until "baseurl:"
  Random ramblings of a random developer
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://saichand.github.io/" # the base hostname & protocol for your site
twitter_username: sinkercat
github_username:  saichand

# Build settings
markdown: kramdown
